### ISSUE TITLE
improve ui

### ISSUE THREAD

**Issue by nmogrady** [myMailMate/mailmate#3]

**Comment by dwesty23** [comment]
Ok here are my thoughts for improving the UI:

1. For starters, whatever UI library Alexis/Bhavik have in mind I'm sure it looks sick so for colors and fonts let's just go with that.
2. 
![Screenshot 2024-11-14 at 5 08 26 PM](https://github.com/user-attachments/assets/b69a77fc-4630-4446-96b8-60f958c17855)
Clean this up a bit obvi

3. 
![Screenshot 2024-11-14 at 5 08 50 PM](https://github.com/user-attachments/assets/79661778-f532-481b-83ea-414d70dc60c4)
Ok instead of breaking down the user inputs into TO, CC, BODY, etc. Lets just have them all be under 1 section: User input fields. Then, instead of having the titles be TO: or Reciever: lets have the code be something more human-readable. Instead of just TO: maybe Who is this email being sent to? etc. Have this be coded by the user like {@email: Who is this email being sent to?} or something like that.

4. Notice the delivery date and receiver on that last screenshot. It's the same value. To reduce redundancy, if a user puts the same tag twice, only generate 1 input for it to save time.

lmk what others think but these are my initial ideas
